add snmp-ping function that might work
git-svn-id: http://svn.vanstaveren.us/trick_skel@928 434ebc3a-ad12-0410-8bf5-d84fc7825958

diff --git a/skel/.trick_skel/sh-startup/60-snmp-functions b/skel/.trick_skel/sh-startup/60-snmp-functions
--- a/skel/.trick_skel/sh-startup/60-snmp-functions
+++ b/skel/.trick_skel/sh-startup/60-snmp-functions
@@ -58,4 +58,11 @@ trick_skel_snmp() {
     snmpwalk -v2c -c public $*
 }
 
+snmp-ping() {
+    trick_skel_snmp $1 SNMPv2-MIB::sysUpTime
+    if [ $? -ne 0 ]; then
+        echo "SNMP uptime query failed. Make sure this host is accepting connections from this IP, and that the community is public."
+    fi
+}
+
 # vim:ft=sh
