make this variable
git-svn-id: http://svn.vanstaveren.us/trick_skel@895 434ebc3a-ad12-0410-8bf5-d84fc7825958

diff --git a/install.d/99-warn-missing-packages b/install.d/99-warn-missing-packages
--- a/install.d/99-warn-missing-packages
+++ b/install.d/99-warn-missing-packages
@@ -1,6 +1,10 @@
 #!/usr/bin/env bash
 
-which less &> /dev/null
-if [ $? -ne 0 ]; then
-    echo "MISSING PACKAGE: less"
-fi
+commands="less svn"
+
+for command in $commands; do
+    which $command &> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "MISSING PACKAGE: $command"
+    fi
+done
