New version of ips
git-svn-id: http://svn.vanstaveren.us/trick_skel@898 434ebc3a-ad12-0410-8bf5-d84fc7825958

diff --git a/skel/bin/ips b/skel/bin/ips
--- a/skel/bin/ips
+++ b/skel/bin/ips
@@ -1,3 +1,35 @@
 #!/usr/bin/env bash
 
-ifconfig bce1 | grep inet
+which ipcalc &> /dev/null
+if [ $? -ne 0 ]; then
+    echo "You need to install ipcalc."
+    exit 1
+fi
+
+interfaces="bce1 bce0 vlan2"
+for interface in $interfaces; do
+    ifconfig $interface 2> /dev/null | grep inet &> /dev/null
+    if [ $? -eq 0 ]; then
+        break;
+    fi
+    interface=""
+done
+
+if [ "$interface" = "" ]; then
+    echo "Unable to find interface to grok; I checked $interfaces."
+    exit 1
+fi
+
+ips=`ifconfig $interface | grep inet`
+export IFS=$'\n'
+for line in $ips; do
+    ip=`echo $line | awk '{print $2}'`
+    netmask=`echo $line | awk '{print $4}'`
+    ipcalc_args="--nocolor $ip/$netmask"
+    net=`ipcalc --nocolor $ip/$netmask | grep ^Network | awk '{print $2}'`
+    host_min=`ipcalc --nocolor $ip/$netmask | grep HostMin | awk '{print $2}'`
+    host_max=`ipcalc --nocolor $ip/$netmask | grep HostMax | awk '{print $2}'`
+    echored "$ip "
+    echoblue "($net: $host_min - $host_max)"
+    echo
+done
